name: pawsitive_vibe_finder
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.33
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  get_it: ^8.0.3
  auto_route: ^10.1.0+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true
  generate: true
